# This file defines the CI/CD pipeline to build and deploy the application

steps:
  # Build the main image, but push the image to gcr
  - name: 'gcr.io/cloud-builders/docker'
    id: Building the base program image
    args: [
      'build',
      '-t',
      'gcr.io/development-303600/data_funnel:unverified',
      '--cache-from', 'gcr.io/development-303600/data_funnel:unverified'
      '.'
    ]

  # Build the tests image
  - name: 'gcr.io/cloud-builders/docker'
    id: Building the tests program image
    args: ['build',
           '-t',
           'gcr.io/development-303600/data_funnel_test',
           '--cache-from', 'gcr.io/development-303600/data_funnel_test:unverified'
           '.']

#   Check the code quality
  - name: 'gcr.io/development-303600/data_funnel_test:unverified'
    id: Checking code quality with pylint
    entrypoint: "/bin/sh"
    args: [ "tests/pylint_check.sh" ]

  # Run the unit tests
  - name: 'data_funnel_test'
    id: Running Unit Tests
    args: ['/data_funnel/tests/run_tests.sh']

  # Re-tag the image
  - name: 'gcr.io/cloud-builders/docker'
    id: Tag the main docker image
    args: [ 'tag', 'data_funnel', 'gcr.io/development-303600/data_funnel:$COMMIT_SHA' ]

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    id: Push the docker image
    args: [ 'push', 'gcr.io/development-303600/data_funnel:$COMMIT_SHA' ]

  # Deploy the container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy the container image to Cloud Run
    args:
      - 'run'
      - 'deploy'
      - 'data-funnel'
      - '--image'
      - 'gcr.io/development-303600/data_funnel:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY
#
#images:
#- 'gcr.io/weather-website-255501/data_funnel:$COMMIT_SHA'